apiVersion: apps/v1
kind: Deployment
metadata:
  name: curing-server
  labels:
    app: curing-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curing-server
  template:
    metadata:
      labels:
        app: curing-server
    spec:
      containers:
      - name: server
        image: ghcr.io/entlein/curiourserver:latest@sha256:eba23a1b77ae5c5227fd98bf5ee32f096dc71381325b90a99dbaad87813c1014
        ports:
        - containerPort: 8888
          name: tcp
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        
---
apiVersion: v1
kind: Service
metadata:
  name: curing-server-service
  labels:
    app: curing-server
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: tcp
  selector:
    app: curing-server
